[package]
name = "vello_pacing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
wgpu.workspace = true

[lints]
workspace = true
